upstream uwsgi {
    server unix:/tmp/uwsgi/th-kiforum.sock;
}

server {
	listen 80;
	listen [::]:80;
    server_name 127.0.0.1;
    charset     utf-8;

	root /var/www/html;
	index index.html;

    location /admin {
        uwsgi_pass  uwsgi;
        include     /etc/nginx/uwsgi_params;
    }

    location /api/v1 {
        uwsgi_pass  uwsgi;
        include     /etc/nginx/uwsgi_params;
    }
    
    location /api-auth {
        uwsgi_pass  uwsgi;
        include     /etc/nginx/uwsgi_params;
    }

    location /content {
        uwsgi_pass  uwsgi;
        include     /etc/nginx/uwsgi_params;
    }

    location /static {
        alias /var/www/static;
    }

    location /media {
        alias /var/www/media;
    }

	location / {
		try_files $uri $uri/ =404;
	}
}
