# Generated by Django 5.2.16 on 2026-07-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demonstrator',
            name='key',
            field=models.CharField(max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
