# Generated by Django 5.2.16 on 2026-07-14 13:46

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
